config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :photos, shallow: true do
    member do
      get  :capture
      get  :frame
      post :sms
      get :view
    end
  end

  resources :photo_sets, shallow: true do
    member do
      get :sms
      post :submit
    end
  end

  # Sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'photo_sets#index'
end

app/models/photo_set.rb
class PhotoSet < ActiveRecord::Base

  belongs_to :frame

  before_save :decode_base64_image

  has_attached_file :photo1, :styles => { :medium => "640x480" }
  has_attached_file :photo2, :styles => { :medium => "640x480" }
  has_attached_file :photo3, :styles => { :medium => "640x480" }
  has_attached_file :photo4, :styles => { :medium => "640x480" }
  has_attached_file :photo5, :styles => { :medium => "640x480" }
  has_attached_file :photo6, :styles => { :medium => "640x480" }
  has_attached_file :photo7, :styles => { :medium => "640x480" }
  has_attached_file :photo8, :styles => { :medium => "640x480" }
  has_attached_file :gif,    :styles => { :medium => "640x480" }


  validates_attachment_content_type :photo1, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo2, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo3, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo4, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo5, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo6, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo7, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo8, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :gif,    :content_type => /\Aimage\/.*\Z/

  def stitch(photo, new_frame)
    photo_framing = []
    photo_framing << photo.url.gsub("https", "http")
    photo_framing << new_frame.content.url.gsub("https", "http")
    photo_list = Magick::ImageList.new(*photo_framing)

    flattened = photo_list.flatten_images
    photo_name = "Framing-#{Random.new.rand(500)}-#{photo.original_filename}"
    flattened.write photo_name
    open photo_name
  end

  def apply_frame!
    self.photo1 = stitch photo1, frame
    self.photo2 = stitch photo2, frame
    self.photo3 = stitch photo3, frame
    self.photo4 = stitch photo4, frame
    self.save
    self.save_gif!
  end

  def to_image_array
    image_urls = []
    image_urls << photo1.url.gsub("https", "http") if photo1.present?
    image_urls << photo2.url.gsub("https", "http") if photo2.present?
    image_urls << photo3.url.gsub("https", "http") if photo3.present?
    image_urls << photo4.url.gsub("https", "http") if photo4.present?
    image_urls << photo5.url.gsub("https", "http") if photo5.present?
    image_urls << photo6.url.gsub("https", "http") if photo6.present?
    image_urls << photo7.url.gsub("https", "http") if photo7.present?
    image_urls << photo8.url.gsub("https", "http") if photo8.present?
    image_urls
  end

  def to_image_list
    Magick::ImageList.new(*to_image_array)
  end

  def to_mp4
    animation = Magick::ImageList.new
    animation.ticks_per_second = 60
    to_image_array.each{ |frame|
      animation.push(frame)
      animation.cur_image.delay = 2
    }
    animation.write("animation-#{id}.mp4")
  end

  def save_gif!
    gif_id = "animated-#{self.id}.gif"
    self.to_image_list.write(gif_id)
    self.gif = open(gif_id)
    self.save
  end

  def send_sms
    shortened_link = UrlShortener.shorten self.gif.url, mdn: self.mdn
    Messages.submit "Here is your photo: #{shortened_link}", self.mdn, "63901"
  end

  private

    def decode_base64_image
      if photo1_base64.present?
        data = StringIO.new(Base64.decode64(photo1_base64.split(',')[1]))
        data.class_eval do
          attr_accessor :content_type, :original_filename
        end
        data.content_type      = "image/png"
        data.original_filename = "snapshot1.png"
        self.photo1 = data
        self.photo1_base64 = nil
      end

      if photo2_base64.present?
        data = StringIO.new(Base64.decode64(photo2_base64.split(',')[1]))
        data.class_eval do
          attr_accessor :content_type, :original_filename
        end
        data.content_type      = "image/png"
        data.original_filename = "snapshot2.png"
        self.photo2 = data
        self.photo2_base64 = nil
      end

      if photo3_base64.present?
        data = StringIO.new(Base64.decode64(photo3_base64.split(',')[1]))
        data.class_eval do
          attr_accessor :content_type, :original_filename
        end
        data.content_type      = "image/png"
        data.original_filename = "snapshot3.png"
        self.photo3 = data
        self.photo3_base64 = nil
      end

      if photo4_base64.present?
        data = StringIO.new(Base64.decode64(photo4_base64.split(',')[1]))
        data.class_eval do
          attr_accessor :content_type, :original_filename
        end
        data.content_type      = "image/png"
        data.original_filename = "snapshot4.png"
        self.photo4 = data
        self.photo4_base64 = nil
      end

      if photo5_base64.present?
        data = StringIO.new(Base64.decode64(photo5_base64.split(',')[1]))
        data.class_eval do
          attr_accessor :content_type, :original_filename
        end
        data.content_type      = "image/png"
        data.original_filename = "snapshot4.png"
        self.photo5 = data
        self.photo5_base64 = nil
      end

      if photo6_base64.present?
        data = StringIO.new(Base64.decode64(photo6_base64.split(',')[1]))
        data.class_eval do
          attr_accessor :content_type, :original_filename
        end
        data.content_type      = "image/png"
        data.original_filename = "snapshot4.png"
        self.photo6 = data
        self.photo6_base64 = nil
      end

      if photo7_base64.present?
        data = StringIO.new(Base64.decode64(photo7_base64.split(',')[1]))
        data.class_eval do
          attr_accessor :content_type, :original_filename
        end
        data.content_type      = "image/png"
        data.original_filename = "snapshot4.png"
        self.photo7 = data
        self.photo7_base64 = nil
      end

      if photo8_base64.present?
        data = StringIO.new(Base64.decode64(photo8_base64.split(',')[1]))
        data.class_eval do
          attr_accessor :content_type, :original_filename
        end
        data.content_type      = "image/png"
        data.original_filename = "snapshot4.png"
        self.photo8 = data
        self.photo8_base64 = nil
      end
    end
end

app/controllers/photo_sets_controller.rb
class PhotoSetsController < ApplicationController



  def index
    @photos = PhotoSet.last(8).map { |p| p.gif.url }
  end

  def new
    @photo_set = PhotoSet.new
    @spinner = PhotoSet.last(1).map { |p| p.gif.url }
  end

  def edit
    @photo_set = PhotoSet.find(params[:id])
    @frames = Frame.find_each
  end

  def create
    @photo_set = PhotoSet.create! photo_set_params
    @photo_set.save_gif!
    redirect_to edit_photo_set_url(@photo_set)
  end

  def show
    @photo_set = PhotoSet.find(params[:id])
  end

  def update
    @photo_set = PhotoSet.find(params[:id])
    @photo_set.update(photo_set_params)
    redirect_to sms_photo_set_url(@photo_set)
  end

  def sms
    @photo_set = PhotoSet.find(params[:id])
  end

  def submit
    puts params
    @photo_set = PhotoSet.find(params[:id])
    @photo_set.update(mdn: params[:mdn])
    ApplyAndSendWorker.perform_async(@photo_set.id)
    redirect_to @photo_set
  end

  private

    def photo_set_params
      params.require(:photo_set).permit(:photo1_base64, :photo2_base64, :photo3_base64, :photo4_base64, :photo5_base64, :photo6_base64, :photo7_base64, :photo8_base64, :frame_id, :mdn)
    end

end

app/helpers/photo_sets_helper.rb
module PhotoSetsHelper
end

app/views/photo_sets/edit.html.erb
<div id='gif-row'>
  <div id='gif-frame'>
    <%= image_tag @photo_set.gif.url %>
    <%= image_tag "", class: 'current-frame' %>
  </div>
</div>

<div id='frames-row'>
  <div id='back-frame'>
    <a href="<%= new_photo_set_url %>"><h3>BACK</h3></a>
  </div>
  <div id='frames-frame'>
    <% @frames.each do |frame| %>
      <img class='gif-frame' src='<%= frame.content.url %>' id='<%= frame.id %>'/>
    <% end %>
  </div>
  <div id="next-frame">
    <a id='form-submit' href='#'><h3>NEXT</h3></a>
  </div>
</div>

<div class='hidden'>
  <%= form_for(@photo_set) do |f| %>
    <%= f.hidden_field :frame_id %>
  <% end %>
</div>

<script type='text/javascript'>
$(function() {

  $(".gif-frame").on('click', function() {
    if($(".current-frame").attr("src") == $(this).attr("src")) {
      $(".current-frame").attr("src", "")
      $("#photo_set_frame_id").val(null)
    } else {
      $(".current-frame").attr("src", $(this).attr("src"))
      $("#photo_set_frame_id").val($(this).attr("id"))
    }
  });

  $("#form-submit").on('click', function() {
    $("form").submit();
  });
});
</script>

app/views/photo_sets/index.html.erb
<div class="row">
	<div class="col-xs-6 col-sm-6 col-md-6">
		<div class='text'>
		  <%= image_tag ("redbox-logo.png"), class: "logo", :width => '30%' %>
		  <h2>LAUNCH PARTY!</h2>
		  <p>Congrats peeps on all your hard work!</p>
		  <%= link_to 'Make a GIF', new_photo_set_url, class: 'btn btn-verizon' %>
		</div>
	</div>
	<div class="col-xs-6 col-sm-6 col-md-6">
		<div class="gif-table">
			<% @photos.each do |photo| %>
				<img src="<%= photo %>" width="262px">
			<% end %>
		</div>
	</div>	
</div>

<div class="spotlight spot1"></div>
<div class="spotlight spot2"></div>	
<script>
	$('.text').addClass('magictime twisterInUp');
	$('.gif-table').addClass('animated fadeIn');
</script>

app/views/photo_sets/new.html.erb
<div id='video-row'>
  <div id='video-frame'>
    <video id="live" autoplay></video>
    <div class='processing' style='display:none;'>
        <% @spinner.each do |spinner| %>
          <img class="spinner" src="http://gph.is/1suiQK1">
        <% end %>
      <!-- <i class='fa fa-refresh fa-spin'></i> -->
      <br/>
      <div class="wait-message">Your time is important to us. Please hold.</div>
    </div>
  </div>
</div>


<div id='controls-row'>
  <div id='capture-frame'>
    <a id='btn-camera' href="#"><%= image_tag 'white-btn.png' %></a>
    <div id='count-label' style='display:none;'></div>
  </div>
  <div id='next-frame'>
    <a id='form-submit' href='#'><%= image_tag 'next.png' %></a>
  </div>
</div>

<div class='hidden'>
  <canvas id='scratch'></canvas>
  <%= form_for @photo_set do |f| %>
    <%= f.hidden_field :photo1_base64 %>
    <%= f.hidden_field :photo2_base64 %>
    <%= f.hidden_field :photo3_base64 %>
    <%= f.hidden_field :photo4_base64 %>
    <%= f.hidden_field :photo5_base64 %>
    <%= f.hidden_field :photo6_base64 %>
    <%= f.hidden_field :photo7_base64 %>
    <%= f.hidden_field :photo8_base64 %>
  <% end %>
</div>

<script>
$(function() {
  Photobooth.init();
});
</script>

<script>
  $('#btn-camera').addClass('animated pulse');
  $('#count-label').addClass('animated flash');
</script>

app/views/photo_sets/show.html.erb
<div class="row">
	<div class="col-xs-6 col-sm-6 col-md-6">
		<div class='text'>
		  <h2>You’re all set!</h2>
		  <p>Your .gif is on the way! You will recieve an<br>SMS link in the next few minutes.</p>
		</div>
	</div>
	<div class="col-xs-6 col-sm-6 col-md-6">
		<div class='image'>
		  <%= image_tag @photo_set.gif.url, class: 'gif-image' %>
		  <%= image_tag @photo_set.frame.content.url, class: 'frame' %>
		</div>
	</div>
</div>

<script>
$(function() {
  setTimeout(function() {
    window.location = "/";
  }, 10000);
});
</script>


<script>
	$('.image').addClass('animated bounceInDown');
</script>

app/views/photo_sets/sms.html.erb
<div id='sms-row'>
  <div id='sms-frame'>
    <h3 class="sms">What's yo phone digits?</h3>
    <%= form_tag(submit_photo_set_url(@photo_set)) do %>
      <%= telephone_field_tag :mdn, @photo_set.mdn, class: 'form-control', placeholder: "Mobile Phone Number" %>
     
    <% end %>
  </div>
</div>

<div align="center">
	<div id="keypad" width="300"></div>
</div>

<script>
$(document).ready(function() {
    $('#keypad').keypad({
        inputField: $('form #mdn'),
        submitButtonText: 'GO'
    });
});
</script>